import RPi.GPIO as GPIO
import time

def main():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setwarnings(False)
    GPIO.setup(11,GPIO.OUT)
    GPIO.setup(12,GPIO.OUT)
    GPIO.setup(13,GPIO.OUT)
    GPIO.setup(15,GPIO.OUT)
    GPIO.setup(16,GPIO.OUT)
    GPIO.setup(29,GPIO.OUT)
    GPIO.setup(31,GPIO.OUT)
    GPIO.setup(33,GPIO.OUT)
    C = GPIO.PWM(11, 50)
    D = GPIO.PWM(12, 50)
    E = GPIO.PWM(13, 50)
    F = GPIO.PWM(15, 50)
    G = GPIO.PWM(16, 50)
    A = GPIO.PWM(29, 50)
    B = GPIO.PWM(31, 50)
    Fsh = GPIO.PWM(33, 50)
    C.start(0)
    D.start(0)
    E.start(0)
    F.start(0)
    G.start(0)
    A.start(0)
    B.start(0)
    Fsh.start(0)
    
    
    Fsh.ChangeDutyCycle(6)
    time.sleep(0.5)
    Fsh.ChangeDutyCycle(2)
    time.sleep(5)
    
    
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    B.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    B.ChangeDutyCycle(3)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(5)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.18)
    Fsh.ChangeDutyCycle(6)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    time.sleep(0.26)
    Fsh.ChangeDutyCycle(2)
    B.ChangeDutyCycle(6)
    time.sleep(0.40)
    Fsh.ChangeDutyCycle(2)
    B.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(1.5)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    time.sleep(0.43)
    
    """
    "loop2"
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(7)
    G.ChangeDutyCycle(7)
    B.ChangeDutyCycle(7)
    time.sleep(0.43)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    B.ChangeDutyCycle(3)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.43)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    C.ChangeDutyCycle(6)
    time.sleep(0.43)
    C.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(0.18)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    Fsh.ChangeDutyCycle(6)
    time.sleep(0.26)
    Fsh.ChangeDutyCycle(2)
    B.ChangeDutyCycle(6)
    time.sleep(0.40)
    Fsh.ChangeDutyCycle(2)
    B.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(0.7)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    time.sleep(1)
    """
    
    C.stop()
    D.stop()
    E.stop()
    F.stop()
    G.stop()
    A.stop()
    B.stop()
    GPIO.cleanup()
    
if __name__ == "__main__":
    main()