import RPi.GPIO as GPIO
import time

def main():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setwarnings(False)
    GPIO.setup(11,GPIO.OUT)
    GPIO.setup(12,GPIO.OUT)
    GPIO.setup(13,GPIO.OUT)
    GPIO.setup(15,GPIO.OUT)
    GPIO.setup(16,GPIO.OUT)
    GPIO.setup(29,GPIO.OUT)
    GPIO.setup(31,GPIO.OUT)
    GPIO.setup(33,GPIO.OUT)
    C = GPIO.PWM(11, 50)
    D = GPIO.PWM(12, 50)
    E = GPIO.PWM(13, 50)
    F = GPIO.PWM(15, 50)
    G = GPIO.PWM(16, 50)
    A = GPIO.PWM(29, 50)
    B = GPIO.PWM(31, 50)
    C.start(0)
    D.start(0)
    E.start(0)
    F.start(0)
    G.start(0)
    A.start(0)
    B.start(0)

    "C Maj Scale"
    C.ChangeDutyCycle(5)
    time.sleep(1)
    C.ChangeDutyCycle(2)
    D.ChangeDutyCycle(4)
    time.sleep(1)
    C.ChangeDutyCycle(0)
    D.ChangeDutyCycle(2)
    E.ChangeDutyCycle(6)
    time.sleep(1)
    D.ChangeDutyCycle(0)
    E.ChangeDutyCycle(2)
    F.ChangeDutyCycle(4)
    time.sleep(1)
    E.ChangeDutyCycle(0)
    F.ChangeDutyCycle(2)
    G.ChangeDutyCycle(6)
    time.sleep(1)
    F.ChangeDutyCycle(0)
    G.ChangeDutyCycle(2)
    A.ChangeDutyCycle(4)
    time.sleep(1)
    G.ChangeDutyCycle(0)
    A.ChangeDutyCycle(2)
    B.ChangeDutyCycle(6)
    time.sleep(1)
    A.ChangeDutyCycle(0)
    B.ChangeDutyCycle(2)
    time.sleep(1)
    B.ChangeDutyCycle(0)
    
    """
    "C-F-G"
    C.ChangeDutyCycle(6)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(1.5)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(4)
    G.ChangeDutyCycle(4)
    time.sleep(0.2)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    B.ChangeDutyCycle(6)
    time.sleep(0.8)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    B.ChangeDutyCycle(3)
    time.sleep(0.2)
    D.ChangeDutyCycle(5)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(2)
    D.ChangeDutyCycle(2)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    time.sleep(0.2)
    C.ChangeDutyCycle(6)
    time.sleep(0.5)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(6)
    time.sleep(0.5)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(6)
    time.sleep(0.5)
    G.ChangeDutyCycle(3)
    time.sleep(0.1)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    B.ChangeDutyCycle(6)
    time.sleep(1)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    B.ChangeDutyCycle(3)
    time.sleep(0.2)
    D.ChangeDutyCycle(5)
    F.ChangeDutyCycle(5)
    A.ChangeDutyCycle(5)
    time.sleep(2)
    D.ChangeDutyCycle(2)
    F.ChangeDutyCycle(2)
    A.ChangeDutyCycle(2)
    time.sleep(0.2)
    B.ChangeDutyCycle(6)
    time.sleep(0.5)
    B.ChangeDutyCycle(3)
    A.ChangeDutyCycle(6)
    time.sleep(0.5)
    A.ChangeDutyCycle(3)
    G.ChangeDutyCycle(6)
    time.sleep(0.5)
    G.ChangeDutyCycle(3)
    F.ChangeDutyCycle(5)
    time.sleep(0.5)
    F.ChangeDutyCycle(3)
    C.ChangeDutyCycle(6)
    E.ChangeDutyCycle(6)
    G.ChangeDutyCycle(6)
    time.sleep(2)
    C.ChangeDutyCycle(3)
    E.ChangeDutyCycle(3)
    G.ChangeDutyCycle(3)
    """
    
    C.stop()
    D.stop()
    E.stop()
    F.stop()
    G.stop()
    A.stop()
    B.stop()
    GPIO.cleanup()
    
if __name__ == "__main__":
    main()